### ISSUE TITLE
Java NullPointerException when starting DRL/IPOPP

### ISSUE THREAD

**Issue by trahloff** [aws-samples/aws-groundstation-s3-data-delivery#2]
Hi AWS Team, 

after setting up the stack as documented, I get the following error when trying to initialize and configuring the IPOPP SPA:

~~~bash
ipopp@ip-REDACTED:~$ java - version openjdk version "11.0.21" 2023-10-17
OpenJDK Runtime Environment (build 11.0.21+9-post-Ubuntu-Oubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.21+9-post-Ubuntu-Oubuntu120.04, mixed mode, sharing) 

ipopp@ip-REDACTED: ~$ ~/drl/tools/dashboard.sh &
[1] 57046

ipopp@ip-REDACTED:~$ Exception in thread "main" java. lang-NullPointerException
at java.base/java.io.File.<init>(File.java:278)
at gov.nasa.gsfc.nisgs.nsls.util.D0MUtil. readXMLFile(DOMUtil.java:58)
at gov.nasa.gsfc.nisgs.nsls.console.ControlPanel.<init>(ControlPanel.java:258)
at gov.nasa.gsfc.nisgs.nsls.console.ControlPanel.main(ControlPanel.java:205)
~~~

Looking at `/var/log/user-data.log` of the IPOPP instance, it seems like there are various factors at play here:                                                                                                 

~~~bash
=========================================
Installing IPOPP
=========================================
Region: eu-west-1
S3 Bucket: eu-west-1
Installing IPOPP pre-reqs
/opt/aws/groundstation/bin/install-ipopp.sh: line 27: yum: command not found
/opt/aws/groundstation/bin/install-ipopp.sh: line 28: yum: command not found
/opt/aws/groundstation/bin/install-ipopp.sh: line 29: yum: command not found
/opt/aws/groundstation/bin/install-ipopp.sh: line 30: yum: command not found
/opt/aws/groundstation/bin/install-ipopp.sh: line 31: yum: command not found
/opt/aws/groundstation/bin/install-ipopp.sh: line 32: yum: command not found
/opt/aws/groundstation/bin/install-ipopp.sh: line 33: yum: command not found
/opt/aws/groundstation/bin/install-ipopp.sh: line 34: yum: command not found
~~~

and

~~~bash
An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Acces                                                                                                 s Denied
Starting IPOPP install
mv: cannot stat 'DRL-IPOPP_4.0.tar.gz': No such file or directory
~~~

Do you have any pointers or suggestions for a potential solution? Thanks!

**Comment by trahloff** [comment]
If it makes a difference (because of NASA discontinuing DRL): I still have the myDRL account from back in the days and used this repository successfully in the past (~2021).

**Comment by trahloff** [comment]
Hi @Viktor-Pankov , any idea where the root cause may be? I'm wrecking my brain but somehow cannot pinpoint the issue.

**Comment by Viktor-Pankov** [comment]
Hey Tobias, are you using the latest version of the repo? 
There's been a few changes since your last successful pass in 2021. Please make sure that you are not relying on your old supporting software version that you might still have on S3.

**Comment by Viktor-Pankov** [comment]
Closing issue. 

Tobias, reach out if you have any more questions.
